// This file was generated by the Sentry wizard because we couldn't find a root layout file.
// You can delete this file at any time.

export const metadata = {
  title: {
    template: '%s | AI Free Pool - 免费AI额度聚合平台',
    default: 'AI Free Pool - 免费AI额度聚合平台',
  },
  description: 'Discover and track free AI credits, tokens, and trials from top AI platforms. 发现和追踪各大AI平台的免费额度、Token和试用机会。',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
